version: '3'
services:
    tendersaucer:
        build:
            context: .
            dockerfile: Dockerfile-fullstack
        restart: on-failure
        command: python main.py
        depends_on:
            - mysql
            - redis
            - neo4j
        ports:
            - "5000:5000"
        environment:
            - SPOTIFY_CLIENT_ID
            - SPOTIFY_CLIENT_SECRET
            - MYSQL_USER
            - MYSQL_PASSWORD
            - NEO4J_USER
            - NEO4J_PASSWORD
        networks:
            - tendersaucer_network
    celery:
        build:
            context: .
            dockerfile: Dockerfile-backend
        restart: on-failure
        command: celery -A tendersaucer.tasks worker --loglevel=info
        depends_on:
            - mysql
            - redis
            - neo4j
        environment:
            - SPOTIFY_CLIENT_ID
            - SPOTIFY_CLIENT_SECRET
            - MYSQL_USER
            - MYSQL_PASSWORD
            - NEO4J_USER
            - NEO4J_PASSWORD
        networks:
            - tendersaucer_network
    indexer:
        build:
            context: .
            dockerfile: Dockerfile-backend
        restart: on-failure
        command: /bin/sh -c "PYTHONPATH=. python ./scripts/indexer.py --run-mode discover --num-workers 4"
        depends_on:
            - mysql
            - redis
            - neo4j
        environment:
            - SPOTIFY_CLIENT_ID
            - SPOTIFY_CLIENT_SECRET
            - MYSQL_USER
            - MYSQL_PASSWORD
            - NEO4J_USER
            - NEO4J_PASSWORD
        networks:
            - tendersaucer_network
    neo4j:
        image: neo4j:3.5.3
        restart: on-failure
        ports:
            - "7687:7687"
            - "7474:7474"
            - "7473:7473"
        environment:
            - NEO4J_AUTH=neo4j/root
            - NEO4J_dbms_memory_pagecache_size=1G
            - NEO4J_dbms_memory_heap_max__size=1G
            - NEO4J_dbms_memory_heap_initial__size=1G
        networks:
            - tendersaucer_network
        volumes:
            - neo4j-volume:/data
            - neo4j-logs-volume:/logs
    mysql:
        image: "mysql:5.6"
        restart: on-failure
        ports:
            - "3306:3306"
        networks:
            - tendersaucer_network
        volumes:
            - ./sql:/opt/sql
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - mysql-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    redis:
        image: "redis:3.2.4"
        restart: on-failure
        ports:
            - "6379:6379"
        networks:
            - tendersaucer_network
        volumes:
            - redis-volume:/data
networks:
    tendersaucer_network:
        external: true
volumes:
    redis-volume:
    mysql-volume:
    neo4j-volume:
    neo4j-logs-volume:
